### ISSUE TITLE
Fine-tune the dark theme

### ISSUE THREAD

**Issue by programarivm** [chesslablab/spablab#721]
The dark theme needs some fine-tuning for the MUI table components.

![figure_01](https://github.com/chesslablab/react-chess/assets/4062000/7a8f6d80-be12-410b-acf1-19d01e1e347d)
**Figure 1**. **Database > Search Games**

![figure_02](https://github.com/chesslablab/react-chess/assets/4062000/abfd4d0c-efc2-4831-b161-94f22f7480ed)
**Figure 2**. **Database > Annotated Games**

**Comment by HappyLife2** [comment]
.take

**Comment by HappyLife2** [comment]
After creating the environment and doing all the steps it gave me this error and the certificate is not valid, may I know how to fix it?

Screenshot of the issue:
![Screenshot 2024-02-11 154008](https://github.com/chesslablab/react-chess/assets/130459769/ef3d6d46-ffe1-40be-af19-22320206e43e)

**Comment by VenusTokyo** [comment]
hello, can i work on this?

**Comment by neeravbhaskarla** [comment]
Hello, can I work on this?

**Comment by neeravbhaskarla** [comment]
Hi @programarivm. I have fixed this issue of my fork. If I got this issue assigned, will raise PR asap. Thank you.

**Comment by programarivm** [comment]
@neerav welcome to ChesslaBlab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/spablab/blob/main/CONTRIBUTING.md).

Happy learning!

**Comment by neeravbhaskarla** [comment]
hi @programarivm, Submitted PR. Please review it.
